using System;
using SQLite.Net.Attributes;
using SQLite.Net;
using System.ComponentModel;
using System.Collections.Generic;
using TimingApp.Data.Internal.SQLite.Model;

namespace TimingApp.Data.Internal.SQLite 
{
	static class DatabaseUtils
	{
		// HACK: this should be false for all bar occasional runs 					
		static bool StartFresh = true;

		public static T DoAction<T, T1>(this Func<SQLiteConnection, T> action)
		{

			using(var connection = new TimingDatabase().Connection)
			{
				if(StartFresh)
				{
					connection.DropTable<DbTimingItem>();
					connection.DropTable<DbBoat>();
					connection.DropTable<DbRace>();
					StartFresh = false; // otherwise it would be continually dropping the tables ... 

					connection.CreateTable<DbTimingItem>();
					connection.CreateTable<DbBoat>();
					connection.CreateTable<DbRace>();

					connection.Execute ("insert into Races (_code, _name) values (?, ?)", "adhoc", "AdHoc Race");
					connection.Execute ("insert into Races (_code, _name) values (?, ?)", "vh14", "Vets Head 2014");
					connection.Execute ("insert into Races (_code, _name) values (?, ?)", "ph14", "Pairs Head 2014");
					connection.Execute ("insert into Races (_code, _name) values (?, ?)", "sh14", "Scullers Head 2014");

					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 1, "Thames RC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 2, "Broxbourne RC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 3, "C N Betulo (ES)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 4, "Bristol Ariel/Tyne RC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 5, "Quintin BC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 6, "Parr's Priory");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 7, "STCRC (DE)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 8, "Cercla Nautique de France (FR)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 9, "Kar & Zv De Hoop (NL)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 10, "Agecroft");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 11, "York City");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 12, "Corgeno Sc (IT)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 13, "RCR Alicante (ES)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 14, "Royal Maas YC (NL)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 15, "Tyrian Club/Thames RC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 16, "Canottieri Ravenna (IT) [Lunghi]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 17, "Cygnet RC");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 18, "Canottieri Ravenna (IT) [Pelligra]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 19, "S C Armida (IT)");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 20, "Crabtree");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "vh14", 21, "Monmouth RC");

					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 1, "Crew 1");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 2, "Crew 2");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 3, "Crew 3");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 4, "Crew 4");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 5, "Crew 5");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 6, "Crew 6");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 7, "Crew 7");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 8, "Crew 8");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 9, "Crew 9");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 10, "Crew 10");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 11, "Crew 11");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 12, "Crew 12");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 13, "Crew 13");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 14, "Crew 14");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 15, "Crew 15");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 16, "Crew 16");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 17, "Crew 17");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 18, "Crew 18");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 19, "Crew 19");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 20, "Crew 20");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "adhoc", 21, "Crew 21");

					connection.Execute ("insert into TimingItems (_race, _location, _token, _time, _startNumber, _notes) values (?, ?, ?, ?, ?, ?)", "adhoc", "Start", "abcd", new DateTime (2014, 4, 1, 12, 12, 13), 1, string.Empty);
					connection.Execute ("insert into TimingItems (_race, _location, _token, _time, _startNumber, _notes) values (?, ?, ?, ?, ?, ?)", "adhoc", "Finish", "abcd", new DateTime (2014, 4, 1, 13, 1, 3), 1, string.Empty);

					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 1, "[Tideway Scullers School / A Ridler / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 2, "[London RC / E Coakley / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 3, "[Burway RC / J Barrett / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 4, "[Upper Thames RC / T Carter / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 5, "[Crabtree / G Pooley / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 6, "[London RC / S Blake / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 7, "[Hollingworth Lake / G Kershaw / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 8, "[Army RC / L Wells / ELI]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 9, "[Norwich RC / V Audinis / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 10, "[Hollingworth Lake / R Handley / IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 11, "[City of Cambridge  / B Redman / IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 12, "[Kings School Canterbury / J Williamson / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 13, "[Sons of the Thames / S Haeata / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 14, "[Tideway Scullers School / D Rogal / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 15, "[Auriol Kensington / F Raschke / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 16, "[Twickenham RC / K Kolimechkov / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 17, "[Ardingly / A Dombrowe / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 18, "[Upton RC / J Scrivener / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 19, "[Rob Roy / S Graf / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 20, "[Thames RC / J Burke / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 21, "[Quintin BC / M Denley / IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 22, "[Cardiff City / D George / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 23, "[Itchen Imperial RC / T Foad / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 24, "[Maidenhead RC / R Fulton / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 25, "[Rob Roy / C Owen / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 26, "[Cardiff City / H Carrick / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 27, "[Henley RC / E Hillyard / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 28, "[Walbrook / P Lukes / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 29, "[RAF / T Ellis / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 30, "[Rob Roy / S Butlin / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 31, "[London RC / R McGow / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 32, "[Sudbury RC / T Bowles / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 33, "[Kings School Canterbury / R Hosking / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 34, "[Barcelona C. De Rem (ES) / M Garcia  / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 35, "[Auriol Kensington / N Von Kaltenborn / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 36, "[Rob Roy / R Oeffner / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 37, "[Maidstone Invicta / J Knight / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 38, "[Quintin BC / L Jacobsen / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 39, "[Granta / P Copham / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 40, "[Bewl Bridge / M Northwood / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 41, "[Wallingford RC / S Morris / MasH]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 42, "[Barcelona C. De Rem (ES) / I Hidalgo / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 43, "[Wallingford RC / C Parry / MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 44, "[Hollingworth Lake / T Booth / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 45, "[Quintin BC / S Aquilina / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 46, "[Wycliffe College / A Mitchell / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 47, "[Ardingly / D Vincent / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 48, "[Ardingly / I Andrews / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 49, "[Walton RC / M Bishop / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 50, "[Quintin BC / C Harrison / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 51, "[Quintin BC / T Bishop / MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 52, "[City of Bristol RC / M Downey / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 53, "[Grosvenor RC / P Johnston / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 54, "[Walton RC / P Thiemann / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 55, "[Gloucester RC / M Jones / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 56, "[City of Bristol RC / G Downey / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 57, "[Maidenhead RC / R Macrae / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 58, "[London RC / E Grace / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 59, "[Ardingly / M Howe / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 60, "[Gloucester RC / G Scott / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 61, "[Gloucester RC / R Thornton / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 62, "[Quintin BC / G Potts / MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 63, "[Ardingly / S Radosevic / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 64, "[Norwich RC / E English / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 65, "[Reading RC / D Coneybeare / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 66, "[Cygnet RC / N Bates / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 67, "[Molesey BC / C Bowman / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 68, "[Walbrook / J O Driscoll / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 69, "[Reading RC / S Pollok-Morris / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 70, "[Tideway Scullers School / D Beadle / W.IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 71, "[Walton RC / A Jackson / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 72, "[City of Cambridge  / S Airey / W.IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 73, "[Tideway Scullers School / C Matthews / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 74, "[Star Club / R Armstrong / W.IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 75, "[City of Bristol RC / H Fullman    / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 76, "[Barnes Bridge Ladies / K Baldwin / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 77, "[Wycliffe College / S Payne / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 78, "[Tideway Scullers School / S Dutreux / W.IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 79, "[Mortlake AABC / K Rolfsman / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 80, "[Star Club / J Johnston / W.IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 81, "[Bristol Ariel / U Bauer / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 82, "[Tideway Scullers School / S Supple / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 83, "[Rob Roy / C Revell / ELI]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 84, "[Tideway Scullers School / S Heap / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 85, "[London RC / N Parnell / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 86, "[Portuguese RF (PT) / T Costa / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 87, "[Portuguese RF (PT) / C Cruz / ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 88, "[Tideway Scullers School / C Clarke / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 89, "[Thames Valley Park / S Gough / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 90, "[Tideway Scullers School / D Dalmau / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 91, "[Wallingford RC / D Harvey / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 92, "[Aberdeen BC / J Montgomery / SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 93, "[Bristol Ariel / M Baxter / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 94, "[City of Bristol RC / A Pascovitch / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 95, "[Team Keane / P Keane  / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 96, "[Tideway Scullers School / J Woolley / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 97, "[Quintin BC / A Miller / MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 98, "[Leicester RC / D Smith / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 99, "[Quintin BC / H Powell / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 100, "[Twickenham RC / B van Wachem / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 101, "[Monmouth RC / A Butler / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 102, "[Maidenhead RC / C Breen / MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 103, "[Nottingham RC / N Spencer / W.ELI]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 104, "[Portuguese RF (PT) / J Branco / W.ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 105, "[Portuguese RF (PT) / I Pocinho / W.ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 106, "[Portuguese RF (PT) / I Durães / W.ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 107, "[Tideway Scullers School / R Humphreys / W.ELI.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 108, "[Imperial College / S Theodorou / W.SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 109, "[Tideway Scullers School / E Johnstone / W.SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 110, "[London RC / M Jackson / W.SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 111, "[Thames RC / B Sheldrick / W.SEN]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 112, "[Monmouth RC / M Stewart-Woods / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 113, "[Wallingford RC / S Anderson / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 114, "[Tideway Scullers School / W Fields / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 115, "[Vesta Rowing Club / J Brown / IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 116, "[Boston RC / A Berry / IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 117, "[Bristol Ariel / M Hutchings / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 118, "[Itchen Imperial RC / M Wardell / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 119, "[Tideway Scullers School / N O Reilly / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 120, "[London RC / H Bullough / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 121, "[Walbrook / G Galavotti / IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 122, "[Quintin BC / A Cowley / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 123, "[Portuguese RF (PT) / C Pinto / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 124, "[Itchen Imperial RC / L O Toole / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 125, "[Reading RC / C Iddon / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 126, "[Gloucester RC / P Dewhurst / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 127, "[Reading RC / T Fairclough / J18]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 128, "[Bristol Ariel / K Hall / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 129, "[Twickenham RC / J Lupson / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 130, "[Medway Towns RC / R Aisthorpe / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 131, "[Quintin BC / E Kirk / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 132, "[Thames RC / J Harris / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 133, "[Tideway Scullers School / Z Gullen / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 134, "[Mortlake AABC / C Hart / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 135, "[Vesta Rowing Club / K Burnell / W.MasA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 136, "[Mortlake AABC / A Ramsden / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 137, "[Reading RC / R Cambio / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 138, "[Tideway Scullers School / J Schulz / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 139, "[Quintin BC / D Mallinson / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 140, "[Bristol Ariel / J Vanbeck / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 141, "[Maidstone Invicta / K Povall / W.MasB]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 142, "[Tideway Scullers School / R Davies / W.IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 143, "[Tideway Scullers School / J Brown / W.IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 144, "[Boston RC / E Feerick / W.IM1]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 145, "[Thames RC / S Hodgson / W.IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 146, "[Quintin BC / T Wedlake-James / W.IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 147, "[Marlow RC / N Balhi / W.IM1.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 148, "[Runcorn / A Brighton / W.IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 149, "[Aberdeen BC / K Meston / W.IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 150, "[Poplar Blackwall & District / A Stock / W.IM2]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 151, "[Kings School Canterbury / J Phillips / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 152, "[Maidstone Invicta / B Humphris / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 153, "[Medway Towns RC / S Martin / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 154, "[Walbrook / E Williams / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 155, "[Cygnet RC / G Du Parc Braham / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 156, "[Furnivall SC / C Lewis / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 157, "[Putney Town RC / C Harvey-Judd / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 158, "[Quintin BC / D Ohrenstein / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 159, "[Putney Town RC / V Goerz / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 160, "[Walton RC / C Leonard / MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 161, "[Nemesis BC / D Richardson / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 162, "[Putney Town RC / J Holmes-Siedle / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 163, "[Cotswold RC / A Hynes / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 164, "[Walbrook / N Thomas / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 165, "[Walton RC / I Robinson / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 166, "[Mortlake AABC / D Grylls / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 167, "[Walton RC / G Groom / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 168, "[Royal Chester / G Miller / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 169, "[Marlow RC / M Parsons / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 170, "[Maidenhead RC / T Hudson / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 171, "[Maidenhead RC / K Dixon / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 172, "[Walton RC / M Everington / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 173, "[Bewl Bridge / J Morris / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 174, "[Twickenham RC / P McCarter / MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 175, "[Fulham Reach / D Fitzherbert / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 176, "[Stourport BC / D Gwilliam / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 177, "[London RC / R Metcalf / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 178, "[Champion of the Thames (Cambridge) / S Millar / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 179, "[Molesey BC / D Jillings / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 180, "[Weybridge RC / G Thomas / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 181, "[Weybridge RC / D Feather / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 182, "[Thames RC / K Watkiss / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 183, "[Thames RC / M Panter / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 184, "[Putney Town RC / A Marengo / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 185, "[Molesey BC / B Raspin / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 186, "[Tideway Scullers School / D Best / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 187, "[Hollingworth Lake / P Clay / MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 188, "[Upper Thames RC / G Lloyd / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 189, "[Poplar Blackwall & District / R Milligan / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 190, "[Ardingly / S Banks / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 191, "[Putney Town RC / G Adams / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 192, "[Putney Town RC / S Rose / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 193, "[Thames RC / C Curtis / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 194, "[Gloucester RC / M Venn / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 195, "[City of Oxford / S Spowart / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 196, "[Reading RC / N Smith / MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 197, "[Rob Roy / A Bosnyak / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 198, "[Tideway Scullers School / K Hickmott / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 199, "[Mortlake AABC / C Greenhalgh / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 200, "[Poplar Blackwall & District / B Reid / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 201, "[Walbrook / E Murray / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 202, "[Hollingworth Lake / K Riley / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 203, "[Tideway Scullers School / K Robins / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 204, "[Mortlake AABC / J Gapper / W.MasC]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 205, "[Eton Excelsior / K Johnson / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 206, "[Mortlake AABC / C Bell-Syer / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 207, "[Eton Excelsior / F Brewer / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 208, "[Champion of the Thames (Cambridge) / C Mills / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 209, "[Poplar Blackwall & District / V Lenoel / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 210, "[Champion of the Thames (Cambridge) / C Jacklin / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 211, "[Norwich RC / J Barnacle / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 212, "[Tideway Scullers School / C Delmar / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 213, "[Mortlake AABC / L Campbell / W.MasD]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 214, "[Tideway Scullers School / E Tofts / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 215, "[Tideway Scullers School / C French / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 216, "[Eton Excelsior / S Arion / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 217, "[Weybridge RC / R Kornberg / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 218, "[Barnes Bridge Ladies / J Broadhurst / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 219, "[Mortlake AABC / G Mahony / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 220, "[Tideway Scullers School / K Lawrence / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 221, "[Gloucester RC / G Jones / W.MasE]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 222, "[Tideway Scullers School / V Sixsmith / W.MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 223, "[Weybridge RC / A Morris / W.MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 224, "[Tideway Scullers School / J Al-Janabi / W.MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 225, "[Mortlake AABC / L Elms / W.MasF]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 226, "[Putney Town RC / T Green / MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 227, "[Molesey BC / J Parker / MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 228, "[Mortlake AABC / K Williams / MasI]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 229, "[Putney Town RC / M Kingston / MasI]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 230, "[Walbrook / S Eggeman / W.MasG]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 231, "[Worcester RC / S Barnett / W.Ada.LTA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 232, "[Sudbury RC / S Brown / W.Ada.TA]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 233, "[Thames RC / N Mahon / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 234, "[Thames RC / W Thomson / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 235, "[Broadland BC / T Davies / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 236, "[Thames Tradesmen / M Dodd / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 237, "[Maidstone Invicta / R Baldwin / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 238, "[Lea RC / L Moore / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 239, "[Globe / J Noriel / MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 240, "[London RC / A Love / W.MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 241, "[Tideway Scullers School / R Eisdell / W.MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 242, "[Mortlake AABC / J Brown / W.MasA.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 243, "[London RC / S Mendóça / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 244, "[Maidenhead RC / S Whitehead / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 245, "[Quintin BC / M O brien / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 246, "[Bristol Ariel / F Turley / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 247, "[Thames RC / M Santoro / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 248, "[London RC / M Kalakoutis / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 249, "[Bedford RC / M Farley / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 250, "[Medway Towns RC / L Pettipher / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 251, "[Cardiff City / J Bryning / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 252, "[Thames RC / B McSweeney / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 253, "[Thames RC / S Redmond / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 254, "[Auriol Kensington / R Gray-Cheape / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 255, "[London RC / L Van Diggele / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 256, "[Cardiff City / R Forster / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 257, "[City of Bristol RC / M Sweeney / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 258, "[Auriol Kensington / T Morton-Humphreys / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 259, "[Thames RC / J Palmer / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 260, "[Furnivall SC / M De Paoli / NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 261, "[Twickenham RC / J Wooller / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 262, "[Auriol Kensington / S LANFRANCONI / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 263, "[Royal Navy & Royal Marines / J Fickling / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 264, "[Thames RC / T Harvey / IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 265, "[Cardiff City / D John / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 266, "[Magdalen College School / F Exton-Smith / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 267, "[Quintin BC / M Ewing / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 268, "[City of Bristol RC / C Turner / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 269, "[London RC / A Anderson / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 270, "[Auriol Kensington / J Kaczor / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 271, "[Cardiff City / T Hall / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 272, "[Swansea City RC / R Paul / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 273, "[Star Club / B Hunter / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 274, "[Star Club / J Traynor / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 275, "[Sons of the Thames / M Brinker / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 276, "[Eton Excelsior / A Williams / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 277, "[London RC / B Folkard / IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 278, "[Fulham Reach / S Livingstone / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 279, "[Furnivall SC / M Pesola / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 280, "[Auriol Kensington / M Raffaele / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 281, "[Cardiff City / J Marshall / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 282, "[Mortlake AABC / I Papavergos / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 283, "[Lea RC / A Irving / W.NOV]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 284, "[Thames RC / M Foster / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 285, "[Furnivall SC / S Livermore / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 286, "[Globe / A Hickey-Moody / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 287, "[Rob Roy / L Hamilton / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 288, "[Nottingham RC / A MacCartney / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 289, "[Vesta Rowing Club / S Faull / W.IM3]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 290, "[Taunton / A Hallett / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 291, "[London RC / C Duff / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 292, "[Itchen Imperial RC / K McGregor-Ritchie / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 293, "[Quintin BC / N Brown / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 294, "[Twickenham RC / S Field / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 295, "[Hollingworth Lake / L Daniels / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 296, "[Tideway Scullers School / J Belcher / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 297, "[Tideway Scullers School / B Essex / W.IM3.LWT]");
					connection.Execute("insert into Boats (_race, _number, _name) values (?, ?, ?)", "sh14", 298, "[Mortlake AABC / P Delvalle / W.IM3.LWT]");

				}

				connection.CreateTable<T1>();

				var result = action(connection);
				return result;
			}
		}

		public static IEnumerable<T> GetAll<T>() where T : new() 
		{
			return DatabaseUtils.DoAction<IList<T>, T>((SQLiteConnection connection) => 
				{
					var t = connection.Table<T>();
					var rv = new List<T>();
					foreach(var q in t)
						rv.Add(q);

					return rv;
				});
		}	
	}
}
